# client options
# ==============
# debug stuff
debug_email: false
smtp_server: SMTP
smtp_port: 25
# File listing bible books. Usually no need to change this.
book_file: 'bibleBooks.yml'
# File used to track the last checked revision. Usually no need to change this.
tracking_file: 'rev_track'
# Connection parameters to the website database.
dbi_url: 'SQLite:dbname=testdb.sqlite'
dbi_user: ''
dbi_pw: ''
# URL to use to retrieve the chapter pages from.
chapter_url: 'http://www.offene-bibel.de/wiki/index.php5?title=%s&action=raw'
# URL used to retrieve the changes in JSON format.
rc_url: 'http://www.offene-bibel.de/wiki/api.php?action=query&list=recentchanges&rcend=%s&rclimit=500&rcprop=title|ids&format=json'
# Whether to run the client in a loop.
loop_client: false
# If run in loop mode, the interval in minutes to poll for new changes.
loop_minutes: 5
# Path to the converter (a `validator.sh` file). In server mode this is the path on the server computer.
validator_path: '/home/patrick/Documents/offeneBibel/eclipse_offbi/workspace/Parser/install/bin/validator.sh'
# Whether to use a separate server process on a foreign computer.
server_mode: false

# The stuff below is only relevant if server_mode is set to true.
# options client/server
# =====================
# Host and port of the server running the *server* process.
host: 'http://patszim.volans.uberspace.de'
port: 63978

